name: microns_env_2024
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - numpy-base
  - pandas
  - xarray
  - h5netcdf
  - matplotlib
  - ipykernel
  - jupyter
  - jupyterlab
  - ipywidgets
  - pip:
      - caveclient
      - meshparty
      - nglui
      - skeleton-plot