Table name: `aibs_column_nonneuronal_ref`

A subset of nucleus detections in a 100 um column (n=2204) in VISp were manually classified by anatomists at the Allen Institute into categories of cell subclasses, first distinguishing cells into classes of non-neuronal, excitatory and inhibitory; then into subclasses.

For the neuronal subclasses, see `allen_v1_column_types_slanted_ref`

The key columns are:

| Column | Description |
| :--- | :--- |
| `id` | Soma ID for the cell |
| `pt_position` \ `pt_supervoxel_id` \ `pt_root_id` | Bound spatial point columns associated with the centroid of the cell nucleus |
| `classification-system`| One of `aibs_coarse_excitatory` or `aibs_coarse_inhibitory` for detected neurons, or `aibs_coarse_nonneuronal` for non-neurons (glia/pericytes).
| `cell_type` | One of several cell types, detailed below |

: AIBS Manual Cell Types, V1 Column {.light .hover}

:::{.callout-tip}
This is a reference table on `nucleus_detection_v0`, and can be indexed by the same nucleus id. 
:::

The cell types in the table are:

::: {.callout-note appearance="minimal" collapse=true}
### Manual Cell Types (non-neurons)
| Cell Type | Subclass | Description |
| :--- | :--- | :--- |
| `OPC` | Non-neuronal | Oligodendrocyte precursor cell | 
| `astrocyte` | Non-neuronal | Astrocyte | 
| `microglia` | Non-neuronal | Microglia | 
| `pericyte` | Non-neuronal | Pericyte | 
| `oligo` | Non-neuronal | Oligodendrocyte | 

: AIBS Manual Cell Type definitions (non-neurons) {.light .hover}

:::

```python
# Standard query
client.materialize.query_table('aibs_column_nonneuronal_ref')

# Content-aware query
client.materialize.tables.aibs_column_nonneuronal_ref(id=example_nucleus_id).query()
```