Table name: `allen_v1_column_types_slanted_ref`

A subset of nucleus detections in a 100 um column (n=2204) in VISp were manually classified by anatomists at the Allen Institute into categories of cell subclasses, first distinguishing cells into classes of non-neuronal, excitatory and inhibitory; then into subclasses.

For the non-neuronal subclasses, see `aibs_column_nonneuronal_ref`

The key columns are:

| Column | Description |
| :--- | :--- |
| `id` | Soma ID for the cell |
| `pt_position` \ `pt_supervoxel_id` \ `pt_root_id` | Bound spatial point columns associated with the centroid of the cell nucleus |
| `classification-system`| One of `aibs_coarse_excitatory` or `aibs_coarse_inhibitory` for detected neurons, or `aibs_coarse_nonneuronal` for non-neurons (glia/pericytes).
| `cell_type` | One of several cell types, detailed below |

: AIBS Manual Cell Types, V1 Column {.light .hover}

:::{.callout-tip}
This is a reference table on `nucleus_detection_v0`, and can be indexed by the same nucleus id. 
:::

The cell types in the table are:

::: {.callout-note appearance="minimal" collapse=true}

### Manual Cell Types (neurons)

| Cell Type | Subclass | Description |
| :--- | :--- | :--- |
| `23P` | Excitatory | Layer 2/3 cells | 
| `4P` | Excitatory | Layer 4 cells | 
| `5P-IT` | Excitatory | Layer 5 **i**ntra**t**elencephalic cells | 
| `5P-ET` | Excitatory | Layer 5 **e**xtra**t**elencephalic cells | 
| `5P-NP` | Excitatory | Layer 5 near-projecting cells | 
| `6P-IT` | Excitatory | Layer 6 **i**ntra**t**elencephalic cells | 
| `6P-CT` | Excitatory | Layer 6 **c**ortico**t**halamic cells | 
| `BC` | Inhibitory | Basket cell | 
| `BPC` | Inhibitory | Bipolar cell. *In practice, this was used for all cells thought to be VIP cell, not only those with a bipolar dendrite* | 
| `MC` | Inhibitory | Martinotti cell. *In practice, this label was used for all inhibitory neurons that appeared to be Somatostatin cell, not only those with a Martinotti cell morphology*| 
| `Unsure` | Inhibitory | Unsure. *In practice, this label also is used for all likely-inhibitory neurons that did not match other types*| 

: AIBS Manual Cell Type definitions (neurons) {.light .hover}

:::


```python
# Standard query
client.materialize.query_table('allen_v1_column_types_slanted_ref')

# Content-aware query
client.materialize.tables.allen_v1_column_types_slanted_ref(id=example_nucleus_id).query()
```