Table name: `baylor_log_reg_cell_type_coarse_v1`

This table contains the results of a logistic regression classifier trained on properties of neuronal dendrites. This was applied to many cells in the dataset, but required more data than soma and nucleus features alone and thus more cells did not complete the pipeline. It has very good performance on excitatory vs inhibitory neurons because it focuses on dendritic spines, a characteristic property of excitatory neurons. It is a good table to double check E/I classifications if in doubt.

For details, see [@celii_neurd_2025].

The key columns are:

| Column | Description |
| :--- | :--- |
| `id` | Soma ID for the cell |
| `pt_position` \ `pt_supervoxel_id` \ `pt_root_id` | Bound spatial point columns associated with the centroid of the cell nucleus |
| `classification-system`| `baylor_log_reg_cell_type_coarse` for all entries |
| `cell_type` | `excitatory` or `inhibitory` |

: Baylor Coarse Cell Type Table {.light .hover}

:::{.callout-tip}
This is a reference table on `nucleus_detection_v0`, and can be indexed by the same nucleus id. 
:::

```python
# Standard query
client.materialize.query_table('baylor_log_reg_cell_type_coarse_v1')

# Content-aware query
client.materialize.tables.baylor_log_reg_cell_type_coarse_v1(id=example_nucleus_id).query()
```