Table name: `functional_properties_v3_bcm`

A summary of the functional properties for each of the coregistered neurons (as of `coregistration_manual_v3`). For details, see [@ding_functional_2025]

The key columns are:

| Column | Description |
| :--- | :--- |
| `target_id` | Soma ID for the cell |
| `pt_position` \ `pt_supervoxel_id` \ `pt_root_id` | Bound spatial point columns associated with the centroid of the nucleus |
| `session` | The session index from functional imaging |
| `scan_idx` | The scan index from functional imaging |
| `unit_id` | The functional unit index from imaging. Only unique within scan and session |
| `pref_ori` | preferred orientation in radians (0 - pi), horizontal bar moving upward is 0 and orientation increases clockwise, extracted from model responses to oriented noise stimuli |
| `pref_dir` | preferred direction in radians (0 - 2pi), horizontal bar moving upward is 0 and orientation increases clockwise, extracted from model responses to oriented noise stimuli |
| `gOSI` | global orientation selectivity index |
| `gDSI`|  global direction selectivity index |
| `cc_abs` | prediction performance of the model, higher is better |

: Fuctional properties of coregistered neurons {.light .hover}

:::{.callout-tip}
This is a reference table on `nucleus_detection_v0`, and can be indexed by the same nucleus id. 
:::

:::{.callout-warning}
This table includes duplicate entries for the same 'pt_root_id' and nucleus id if the coregistered cell has multiple unit recordings
:::

```python
# Standard query
client.materialize.query_table('functional_properties_v3_bcm')

# Content-aware query
client.materialize.tables.functional_properties_v3_bcm(id=example_nucleus_id).query()
```