Table name: `vortex_synapse_reattachment`

This table reports the status of a subset of synapses in the V1 column that were not connected to a postsynaptic soma (as of v1300). All synapses in this table were evaluated for reattachment as part of a VORTEX proofreading pilot. Synapse selection and proofreading performed as part of the [VORTEX project](../vortex-overview.html).

The key columns are:

| Column | Description |
| :--- | :--- |
| `id`/`target_id` | Synapse ID for the previously disconnected synapse. This table is reference on `synapses_pni_2`. |
| `pre_pt_position` / `pre_pt_supervoxel_id` / `pre_pt_root_id` | The bound spatial point data for the presynaptic side of the synapse. |  
| `post_pt_position` / `post_pt_supervoxel_id` / `post_pt_root_id` | The bound spatial point data for the postsynaptic side of the synapse. |  
| `size` | The size of the synapse in voxels. This correlates well, but not perfectly, with the surface area of synapse. |  
| `ctr_pt_position` | A position in the center of the detected synaptic junction. Of all points in the synapse table, this is usually the closest point to the surface (and thus mesh) of both neurons. Because it is at the edge of cells, it is not associated with a root id. |
| `tag` | The final state of synapse attachment, one of: 'spine' indicating the disconnected synapse was a spinehead and successfully attached to a dendrite; 'dendrite' indicating the synapse was part of a disconnected dendrite and successfully attached to the soma; 'disconnected': indicating a real spinehead that could not be connected to a dendrite; and 'error' indicating an error of synapse detection.  |

```python
# Standard query
client.materialize.query_table('vortex_synapse_reattachment')

# Content-aware query
client.materialize.tables.vortex_synapse_reattachment(post_pt_root_id=example_root_id).query()

client.materialize.tables.vortex_synapse_reattachment(tag='spine').query()
```